version: '3'
services:
  # Servicio de la aplicación Node.js
  node_app:
    image: santiscv/crud_final:1.0
    container_name: crud_app
    ports:
      - "3001:3000"  
    depends_on:
      - mysql

    networks:
      - my_network
      
    command: [ "npm", "restart"]
    
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jaimito_351
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:

  